'use client';
import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
const MessageContent=lazy(()=>import('./message-content'));
import { ArrowUp, ArrowUpRight, ArrowRight, BookOpen, GraduationCap, BriefcaseBusiness, Globe2, LayoutGrid, MessageSquare, Plus, Settings2, ShieldCheck, ChevronLeft, Download, CircleAlert, Square, LoaderCircle, Sparkles, BrainCircuit, Award, FolderKanban, CircleDot, FileText, Code2, Target, UserRound, Layers3, CheckCircle2, Trash2, Search } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarTrigger, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarGroup, SidebarGroupLabel, useSidebar } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { agents, type AgentId, type Conversation, type Message, type Run } from '@/lib/agents';
import { filterHubSearch, type HubSearchId } from '@/lib/hub-search';
const icons={faculdade:GraduationCap,concursos:BookOpen,ipe:Globe2,carreira:BriefcaseBusiness};
type Status={authenticated:boolean;aiReady:boolean;storageReady:boolean;provider?:'openai'|'ollama'|'n8n'|null;model?:string;dailyLimit?:number};
type CertificateRecord={id:string;title:string;issuer:string;issued_at:string|null;credential_id:string|null;skills:string[];filename:string;mime_type:string;size_bytes:number;created_at:string};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/hub'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'O serviço está temporariamente indisponível. Tente novamente.'})) as Status & {error?:string;conversations:Conversation[];id:string;messages:Message[];run:Run|null};if(!r.ok)throw new Error(d.error||'Não foi possível concluir. Tente novamente.');return d;}
function Hub(){
 const {setOpenMobile}=useSidebar();
 const [status,setStatus]=useState<Status|null>(null),[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<AgentId|null>(null),[current,setCurrent]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[run,setRun]=useState<Run|null>(null),[settings,setSettings]=useState(false),[loading,setLoading]=useState(true),[searchOpen,setSearchOpen]=useState(false),[careerTab,setCareerTab]=useState<'visao'|'certificados'|'plano'>('visao'),[surface,setSurface]=useState<'cover'|'hub'|'career'|'projects'|'focus'|'library'>('cover');
 const agent=agents.find(a=>a.id===selected),bottom=useRef<HTMLDivElement>(null),generation=useRef(0),pending=useRef<{id:string;key:string;content:string}|null>(null);
 async function refresh(){const d=await api('/conversations');setConversations(d.conversations);}
 useEffect(()=>{api('/status').then(async s=>{setStatus(s);if(s.authenticated&&s.storageReady)await refresh();}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(settings)api('/status').then(setStatus).catch(e=>setError(e.message));},[settings]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[messages.length,run?.status]);
 const choose=useCallback((id:AgentId)=>{if(busy)return;pending.current=null;setSurface('hub');setOpenMobile(false);generation.current++;setSelected(id);setCurrent(null);setMessages([]);setRun(null);setDraft('');setError('');},[busy,setOpenMobile]);
 function openCareer(tab:'visao'|'certificados'|'plano'='visao'){if(busy)return;setCareerTab(tab);setSurface('career');setOpenMobile(false);}
 function openProjects(){if(busy)return;setSurface('projects');setOpenMobile(false);}
 function openFocus(){if(busy)return;setSurface('focus');setOpenMobile(false);}
 function openLibrary(){if(busy)return;setSurface('library');setOpenMobile(false);}
 function home(){if(busy)return;pending.current=null;generation.current++;setSelected(null);setCurrent(null);setMessages([]);setRun(null);setError('');}
 async function open(c:Conversation){if(busy)return;pending.current=null;setOpenMobile(false);const version=++generation.current;setBusy(true);setError('');try{const d=await api('/conversations/'+c.id);if(version!==generation.current)return;setSurface('hub');setSelected(c.agent_id);setCurrent(c.id);setMessages(d.messages);setRun(d.run);setDraft('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!current||run?.status!=='running')return;let disposed=false,inFlight=false;const poll=setInterval(async()=>{if(inFlight)return;inFlight=true;try{const d=await api('/conversations/'+current);if(!disposed){setMessages(d.messages);setRun(d.run);if(d.run?.status!=='running')refresh().catch(()=>{});}}catch(e){if(!disposed)setError((e as Error).message);}finally{inFlight=false;}},1800);return()=>{disposed=true;clearInterval(poll);};},[current,run?.status]);
 async function send(){
 if(!draft.trim()||busy||run?.status==='running')return;
 if(!status?.authenticated){setSettings(true);return;}
 setBusy(true);setError('');
 if(!pending.current||pending.current.content!==draft.trim())pending.current={id:current||crypto.randomUUID(),key:crypto.randomUUID(),content:draft.trim()};
 const attempt=pending.current;
 try{
  if(!current){await api('/conversations','POST',{agentId:selected,id:attempt.id});setCurrent(attempt.id);}
  const d=await api('/conversations/'+attempt.id+'/messages','POST',{content:attempt.content,key:attempt.key});
  setMessages(d.messages);setRun(d.run);setDraft(value=>value.trim()===attempt.content?'':value);pending.current=null;
  await refresh();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function retry(){if(!current)return;setBusy(true);setError('');try{const d=await api('/conversations/'+current+'/retry','POST',{key:crypto.randomUUID()});setRun(d.run);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function cancel(){if(!current||busy)return;const version=generation.current,id=current;setBusy(true);try{const d=await api('/conversations/'+id+'/cancel','POST',{});if(version===generation.current)setRun(d.run);}catch(e){if(version===generation.current)setError((e as Error).message);}finally{setBusy(false);}}
 async function removeConversation(c:Conversation){
  if(busy||!window.confirm(`Apagar a conversa “${c.title}”? Esta ação não pode ser desfeita.`))return;
  setBusy(true);setError('');
  try{
   await api('/conversations/'+c.id,'DELETE',{});
   setConversations(items=>items.filter(item=>item.id!==c.id));
   if(current===c.id){generation.current++;pending.current=null;setCurrent(null);setMessages([]);setRun(null);setDraft('');}
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 function selectSearchResult(id:HubSearchId){
  setSearchOpen(false);
  if(id==='faculdade'||id==='concursos'||id==='ipe'||id==='carreira')choose(id);
  else if(id==='certificados')openCareer('certificados');
  else openProjects();
 }
 useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(true);}};document.addEventListener('keydown',onKeyDown);return()=>document.removeEventListener('keydown',onKeyDown);},[]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'select_hub_agent',title:'Selecionar agente',description:'Abre uma nova conversa com um agente do Gabriel AI Hub. Não envia mensagem.',inputSchema:{type:'object',properties:{agentId:{type:'string',enum:agents.map(a=>a.id)}},required:['agentId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(busy)throw Error('Aguarde a operação atual.');const id=(input as {agentId?:string})?.agentId;if(!agents.some(a=>a.id===id))throw Error('Agente inválido');choose(id as AgentId);await new Promise(resolve=>requestAnimationFrame(resolve));return{selectedAgent:id,messageSent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[busy,choose]);
 const globalError=error&&<div className="global-error" role="alert"><CircleAlert size={18}/>{error}<button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>;
 const searchDialog=<HubSearchDialog key={String(searchOpen)} open={searchOpen} setOpen={setSearchOpen} onSelect={selectSearchResult}/>;
 if(surface==='cover')return <><StudioCover onOpenHub={()=>{setSurface('hub');home();}} onChoose={choose} onOpenCertificates={()=>openCareer('certificados')} onOpenProjects={openProjects} onOpenFocus={openFocus} onOpenLibrary={openLibrary} onOpenSearch={()=>setSearchOpen(true)}/>{globalError}{searchDialog}</>;
 if(surface==='career')return <><CareerSpace tab={careerTab} onTabChange={setCareerTab} onBack={()=>setSurface('cover')} onOpenAgent={()=>choose('carreira')}/>{globalError}{searchDialog}</>;
 if(surface==='projects')return <><ProjectsSpace onBack={()=>setSurface('cover')}/>{globalError}{searchDialog}</>;
 if(surface==='focus')return <><FocusSpace onBack={()=>setSurface('cover')}/>{globalError}{searchDialog}</>;
 if(surface==='library')return <><LibrarySpace onBack={()=>setSurface('cover')}/>{globalError}{searchDialog}</>;
 return <><a className="skip-link" href="#workspace">Pular para o conteúdo</a><Sidebar className="hub-sidebar"><SidebarHeader><button disabled={busy} onClick={()=>setSurface('cover')} className="brand"><span className="brand-mark">G<span>·</span></span><span>Gabriel<span className="brand-sub">AI HUB</span></span></button></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>SEU ESPAÇO</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={!selected} onClick={home}><LayoutGrid/><span>Visão geral</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>AGENTES</SidebarGroupLabel><SidebarMenu>{agents.map(a=>{const Icon=icons[a.id];return <SidebarMenuItem key={a.id}><SidebarMenuButton isActive={selected===a.id} onClick={()=>choose(a.id)}><Icon/><span>{a.name}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu></SidebarGroup><SidebarGroup className="recent-nav"><SidebarGroupLabel>CONVERSAS RECENTES</SidebarGroupLabel><SidebarMenu>{conversations.slice(0,6).map(c=><SidebarMenuItem key={c.id}><div className="recent-row"><SidebarMenuButton className="recent-open" onClick={()=>open(c)} title={c.title}><MessageSquare/><span>{c.title}</span></SidebarMenuButton><button type="button" className="recent-delete" onClick={()=>removeConversation(c)} aria-label={`Apagar conversa: ${c.title}`} title="Apagar conversa"><Trash2/></button></div></SidebarMenuItem>)}</SidebarMenu>{!conversations.length&&<p className="sidebar-empty">Suas conversas aparecerão aqui.</p>}</SidebarGroup></SidebarContent><SidebarFooter><SidebarMenu><SidebarMenuItem><SidebarMenuButton onClick={()=>setSettings(true)}><Settings2/><span>Conexão e acesso</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="profile"><span className="avatar">G</span><div>Gabriel<small>Espaço pessoal</small></div><ShieldCheck size={18}/></div></SidebarFooter></Sidebar>
 <main id="workspace" className="main" tabIndex={-1}><header className="topbar"><div><SidebarTrigger aria-label="Abrir ou fechar menu"/><span>Meu espaço <span className="breadcrumb">/ {agent?.name||'Visão geral'}</span></span></div><button className="private-label" onClick={()=>setSettings(true)}><ShieldCheck size={15}/> Acesso privado</button></header>
 {!selected?<div className="dashboard"><div className="greeting"><div><p className="eyebrow">SEU ESPAÇO DE INTELIGÊNCIA</p><h1>Olá, Gabriel<span className="accent-dot">.</span></h1><p>Qual vai ser o próximo passo de hoje?</p></div><div className="edition">G / AI<span>01 — SEUS AGENTES</span></div></div>
 <div className="section-line"><h2>Um agente para cada objetivo</h2><span>4 especialidades · um só lugar</span></div><div className="agent-grid">{agents.map((a,index)=>{const Icon=icons[a.id];return <button key={a.id} className="agent-card" style={{'--agent':a.color,'--wash':a.wash} as React.CSSProperties} onClick={()=>choose(a.id)}><div className="card-top"><span className="agent-icon"><Icon size={26}/></span><span className="card-number">0{index+1}</span></div><h3>{a.name}</h3><p className="agent-area">{a.area}</p><p className="agent-desc">{a.description}</p><div className="tags">{a.tags.map(t=><span key={t}>{t}</span>)}</div><div className="card-bottom"><span>Iniciar conversa</span><ArrowUpRight size={19}/></div></button>;})}</div>
 <section className="history-section"><div className="section-line"><h2>Continue de onde parou</h2><span>{conversations.length?`${conversations.length} ${conversations.length===1?'conversa':'conversas'}`: 'Seu histórico'}</span></div>{loading?<p className="muted">Carregando seu espaço…</p>:conversations.length?<div className="history-list">{conversations.map(c=><div className="history-item" key={c.id}><button className="history-open" onClick={()=>open(c)}><MessageSquare size={19}/><div><strong>{c.title}</strong><span>{agents.find(a=>a.id===c.agent_id)?.name}</span></div><time>{new Date(c.updated_at).toLocaleDateString('pt-BR')}</time><ArrowUpRight size={18}/></button><button type="button" className="history-delete" onClick={()=>removeConversation(c)} aria-label={`Apagar conversa: ${c.title}`} title="Apagar conversa"><Trash2 size={17}/></button></div>)}</div>:<Empty className="empty-history"><EmptyHeader><EmptyTitle>Sua primeira conversa começa acima.</EmptyTitle><EmptyDescription>Escolha um agente. As conversas salvas ficam aqui para você retomar.</EmptyDescription></EmptyHeader></Empty>}</section><div className="connection-note"><CircleAlert size={18}/><span>{status?.aiReady?`${status.provider==='ollama'?'Ollama local':status.provider==='n8n'?'n8n':'OpenAI'} conectado.`: 'Configure o n8n, OpenAI ou Ollama quando estiver pronto.'}</span><button onClick={()=>setSettings(true)}>Ver conexão <ArrowUpRight size={14}/></button></div></div>
 :<div className="chat-layout"><div className="chat-heading"><button className="back" disabled={busy} onClick={home} aria-label="Voltar ao painel"><ChevronLeft size={20}/></button><span className="agent-icon" style={{background:agent?.wash,color:agent?.color}}>{agent&&(()=>{const Icon=icons[agent.id];return <Icon size={24}/>;})()}</span><div><h1>{agent?.name}</h1><p>{agent?.area}</p></div><Button variant="outline" className="new-chat" aria-label="Nova conversa" onClick={()=>choose(selected)}><Plus size={16}/>Nova conversa</Button></div><div className="messages">{!messages.length&&<div className="chat-empty"><p className="eyebrow">VAMOS COMEÇAR</p><h2>O que você quer trabalhar?</h2><p>{agent?.description}</p><button className="suggestion" onClick={()=>setDraft(agent?.prompt||'')}>{agent?.prompt}<ArrowUpRight size={18}/></button><p className="context-note">Suas conversas ficam salvas no Hub. As respostas usam o motor configurado; a confirmação de memórias ainda está em preparação.</p></div>}{messages.map(m=><article className={'message '+m.role} key={m.id}><span className="message-author">{m.role==='user'?'Você':agent?.name}</span>{m.role==='assistant'?<Suspense fallback={<div>{m.content}</div>}><MessageContent text={m.content}/></Suspense>:<div>{m.content}</div>}</article>)}{run?.status==='running'&&<div className="run-state" role="status"><LoaderCircle className="spin" size={17}/>Preparando a resposta…</div>}{run&&['failed','cancelled'].includes(run.status)&&<div className="run-error" role="alert"><CircleAlert size={18}/><span>{run.error||'Resposta interrompida.'}{(run.error?.includes('saldo da API')||run.error?.includes('sem cota disponível'))&&<a className="billing-link" href="https://platform.openai.com/settings/organization/billing" target="_blank" rel="noopener noreferrer">Ver créditos da API <ArrowUpRight size={14}/></a>}</span><Button variant="outline" disabled={busy||!status?.aiReady} onClick={retry}>Tentar novamente</Button></div>}<div ref={bottom}/></div><div className="composer-area">{!status?.aiReady&&<p className="composer-notice">Você pode salvar sua mensagem. As respostas estarão disponíveis após configurar o motor de IA.</p>}<form className="composer" onSubmit={e=>{e.preventDefault();send();}}><textarea aria-label="Mensagem para o agente" placeholder={`Converse com ${agent?.name}…`} value={draft} maxLength={12000} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div className="composer-actions"><span>Enter para enviar · Shift + Enter para nova linha</span>{run?.status==='running'?<button type="button" onClick={cancel} aria-label="Interromper resposta"><Square size={17}/></button>:<button type="submit" disabled={!draft.trim()||busy||loading} aria-label={status?.aiReady?'Enviar mensagem':'Salvar mensagem'}>{busy?<LoaderCircle size={20} className="spin"/>:<ArrowUp size={20}/>}</button>}</div></form></div></div>}
 {globalError}</main>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="connection-dialog"><DialogHeader><DialogTitle>Conexão e acesso</DialogTitle><DialogDescription>O estado atual do seu Gabriel AI Hub.</DialogDescription></DialogHeader><div className="status-row"><span>Acesso à sua conta</span><strong>{status?.authenticated?'Identificado':'Entre para salvar'}</strong></div>{!status?.authenticated&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="signin">Entrar com ChatGPT</a>}<div className="status-row"><span>Histórico de conversas</span><strong>{status?.storageReady?'Disponível':'Aguardando conexão'}</strong></div><div className="status-row"><span>Motor de IA</span><strong>{status?.aiReady?(status.provider==='ollama'?'Ollama local':status.provider==='n8n'?'n8n':'OpenAI'):'Aguardando escolha'}</strong></div><p className="muted">{status?.aiReady?`Modelo: ${status.model}. Limite: ${status.dailyLimit} tentativas por dia (UTC), incluindo falhas.`:'O Hub está preparado para n8n, OpenAI ou Ollama local. Suas conversas e agentes permanecem os mesmos ao trocar o motor.'}</p>{status?.provider==='openai'&&<p className="muted">A assinatura do ChatGPT e os créditos da API são separados. <a className="billing-link" href="https://platform.openai.com/settings/organization/billing" target="_blank" rel="noopener noreferrer">Consultar créditos da API <ArrowUpRight size={14}/></a></p>}{status?.provider==='ollama'&&<p className="muted">O modelo é executado no computador configurado. O site publicado não acessa automaticamente o Ollama do seu computador.</p>}{status?.provider==='n8n'&&<p className="muted">O n8n recebe as mensagens pelo servidor do Hub. A confirmação de memórias pela interface ainda está em preparação.</p>}<div className="engine-options"><div><strong>n8n</strong><span>Roteamento e agentes especializados do Gabriel AI Hub.</span></div><div><strong>Ollama local</strong><span>Sem cobrança por mensagem; depende do computador ligado e da compatibilidade do modelo.</span></div></div><p className="muted">A pesquisa web e anexos dependem das ferramentas configuradas no n8n.</p>{status?.authenticated&&<a className="export-link" href="/api/hub/export" download><Download size={16}/>Exportar minhas conversas</a>}</DialogContent></Dialog>{searchDialog}
 </>;
}

function HubSearchDialog({open,setOpen,onSelect}:{open:boolean;setOpen:(open:boolean)=>void;onSelect:(id:HubSearchId)=>void}){
 const [query,setQuery]=useState('');
 const results=filterHubSearch(query);
 const [active,setActive]=useState(0);
 const previousFocus=useRef<HTMLElement|null>(null);
 function changeOpen(value:boolean){if(!value){setQuery('');setActive(0);}setOpen(value);}
 const searchIcons={faculdade:GraduationCap,concursos:BookOpen,ipe:Globe2,carreira:BriefcaseBusiness,certificados:Award,projetos:FolderKanban};
 return <Dialog open={open} onOpenChange={changeOpen}><DialogContent className="hub-search-dialog" onOpenAutoFocus={()=>{previousFocus.current=document.activeElement as HTMLElement;}} onCloseAutoFocus={event=>{event.preventDefault();const target=previousFocus.current?.isConnected?previousFocus.current:document.getElementById('workspace');target?.focus();}}><DialogHeader><DialogTitle>Pesquisar no Hub</DialogTitle><DialogDescription>Encontre agentes e espaços de trabalho.</DialogDescription></DialogHeader><div className="hub-search-field"><Search size={19}/><label htmlFor="hub-search-input" className="sr-only">Pesquisar conteúdos do Hub</label><input id="hub-search-input" autoFocus value={query} onChange={event=>{setQuery(event.target.value);setActive(0);}} onKeyDown={event=>{if(event.key==='Escape')changeOpen(false);if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();setActive(index=>(index+(event.key==='ArrowDown'?1:-1)+results.length)%Math.max(results.length,1));}if(event.key==='Enter'&&results[active]){event.preventDefault();onSelect(results[active].id);}}} placeholder="Digite para pesquisar…" autoComplete="off" role="combobox" aria-expanded="true" aria-controls="hub-search-results" aria-autocomplete="list" aria-activedescendant={results[active]?`search-result-${results[active].id}`:undefined}/><kbd>Esc</kbd></div><div id="hub-search-results" className="hub-search-results" role="listbox" aria-label="Resultados da pesquisa">{results.map((item,index)=>{const Icon=searchIcons[item.id];return <button key={item.id} type="button" id={`search-result-${item.id}`} role="option" aria-selected={index===active} onMouseEnter={()=>setActive(index)} onClick={()=>onSelect(item.id)}><span><Icon size={19}/></span><div><strong>{item.title}</strong><small>{item.category}</small></div><ArrowRight size={17}/></button>})}{!results.length&&<div className="hub-search-empty" role="status"><Search size={24}/><strong>Nenhum resultado encontrado</strong><span>Tente buscar por uma área ou espaço do Hub.</span></div>}</div></DialogContent></Dialog>;
}

function CareerSpace({onBack,onOpenAgent,tab,onTabChange}:{onBack:()=>void;onOpenAgent:()=>void;tab:'visao'|'certificados'|'plano';onTabChange:(tab:'visao'|'certificados'|'plano')=>void}){
 const setTab=onTabChange;
 const [certificates,setCertificates]=useState<CertificateRecord[]>([]),[uploadOpen,setUploadOpen]=useState(false),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[certificatesLoaded,setCertificatesLoaded]=useState(false),[certificatesError,setCertificatesError]=useState(''),[certificateReload,setCertificateReload]=useState(0);
 useEffect(()=>{let active=true;fetch('/api/hub/certificates').then(async response=>{const data=await response.json().catch(()=>({error:'Não foi possível carregar seus certificados.'})) as {certificates?:CertificateRecord[];error?:string};if(!response.ok)throw new Error(data.error||'Não foi possível carregar seus certificados.');if(active)setCertificates(data.certificates||[]);}).catch(error=>{if(active)setCertificatesError((error as Error).message);}).finally(()=>{if(active)setCertificatesLoaded(true);});return()=>{active=false};},[certificateReload]);
 async function uploadCertificate(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(uploading)return;const form=event.currentTarget;const formData=new FormData(form);setUploading(true);setUploadError('');
  try{const response=await fetch('/api/hub/certificates',{method:'POST',body:formData});const data=await response.json().catch(()=>({error:'Não foi possível salvar o certificado.'})) as {certificate?:CertificateRecord;error?:string};if(!response.ok||!data.certificate)throw new Error(data.error||'Não foi possível salvar o certificado.');setCertificates(items=>[data.certificate!,...items]);setCertificatesError('');setUploadOpen(false);form.reset();setTab('certificados');}catch(error){setUploadError((error as Error).message);}finally{setUploading(false);}
 }
 return <><main className="career-space" id="workspace">
  <header className="career-nav"><button onClick={onBack} className="career-back"><ChevronLeft size={18}/> Voltar ao Hub</button><span className="career-brand"><span>G</span> CARREIRA & CERTIFICADOS</span><span className="career-private"><ShieldCheck size={15}/> espaço pessoal</span></header>
  <section className="career-hero"><div><p>SEU HISTÓRICO PROFISSIONAL</p><h1>Construa uma trajetória<br/><em>que faça sentido.</em></h1><span>Este espaço reúne o que você aprende, cria e quer alcançar.</span></div><div className="career-compass"><div className="compass-ring"><Target size={31}/></div><p>PRÓXIMO PASSO</p><strong>Definir seu ponto de partida</strong></div></section>
  <section className="career-content" aria-label="Área de carreira e certificados">
   <div className="career-metrics"><article><Award size={21}/><strong>{certificates.length}</strong><span>{certificates.length===1?'certificado registrado':'certificados registrados'}</span></article><article><FolderKanban size={21}/><strong>0</strong><span>projetos organizados</span></article><article><Layers3 size={21}/><strong>0</strong><span>trilhas em andamento</span></article></div>
   <div className="career-tabs" role="tablist" aria-label="Navegação da carreira" onKeyDown={event=>{const keys=['ArrowRight','ArrowLeft','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();const tabs=['visao','certificados','plano'] as const;const index=event.key==='Home'?0:event.key==='End'?2:(tabs.indexOf(tab)+(event.key==='ArrowRight'?1:2))%3;setTab(tabs[index]);document.getElementById(`career-tab-${tabs[index]}`)?.focus();}}><button role="tab" aria-selected={tab==='visao'} id="career-tab-visao" aria-controls="career-panel-visao" tabIndex={tab==='visao'?0:-1} onClick={()=>setTab('visao')}>Visão geral</button><button role="tab" aria-selected={tab==='certificados'} id="career-tab-certificados" aria-controls="career-panel-certificados" tabIndex={tab==='certificados'?0:-1} onClick={()=>setTab('certificados')}>Certificados</button><button role="tab" aria-selected={tab==='plano'} id="career-tab-plano" aria-controls="career-panel-plano" tabIndex={tab==='plano'?0:-1} onClick={()=>setTab('plano')}>Plano de evolução</button></div>
   <div role="tabpanel" id={`career-panel-${tab}`} aria-labelledby={`career-tab-${tab}`}>
   {tab==='visao'&&<div className="career-overview"><article className="career-profile"><div className="profile-placeholder"><UserRound size={25}/></div><div><p>SEU PERFIL</p><h2>A sua história começa aqui.</h2><span>Quando estiver pronto, vamos registrar suas habilidades, experiências e direção profissional.</span></div><button onClick={()=>setTab('plano')}>Definir direção <ArrowRight size={16}/></button></article><div className="career-steps"><article><span>01</span><FileText size={20}/><h3>Reúna suas conquistas</h3><p>Certificados, cursos e experiências que já fizeram parte da sua jornada.</p></article><article><span>02</span><Code2 size={20}/><h3>Mostre o que você cria</h3><p>Projetos acadêmicos, técnicos e pessoais vão formar seu portfólio.</p></article><article><span>03</span><Target size={20}/><h3>Escolha sua direção</h3><p>Transforme seus objetivos em um plano de evolução possível de seguir.</p></article></div></div>}
   {tab==='certificados'&&(!certificatesLoaded?<div className="certificate-loading"><LoaderCircle className="spin" size={20}/> Carregando seus certificados…</div>:certificatesError?<div className="certificate-load-error" role="alert"><CircleAlert size={20}/><p>{certificatesError}</p><button onClick={()=>{setCertificatesLoaded(false);setCertificatesError('');setCertificateReload(value=>value+1);}}>Tentar novamente</button></div>:certificates.length?<div className="certificate-library"><div className="certificate-library-head"><div><p>SEUS CERTIFICADOS</p><h2>Conquistas registradas</h2></div><button onClick={()=>setUploadOpen(true)}><Plus size={17}/> Adicionar certificado</button></div><div className="certificate-list">{certificates.map(certificate=><article key={certificate.id}><span className="certificate-file"><FileText size={23}/></span><div className="certificate-info"><small>{certificate.issuer}</small><h3>{certificate.title}</h3><p>{certificate.issued_at?new Date(certificate.issued_at+'T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):'Data não informada'} · {(certificate.size_bytes/1024/1024).toFixed(1)} MB</p>{certificate.skills.length>0&&<div>{certificate.skills.map(skill=><span key={skill}>{skill}</span>)}</div>}</div><a href={`/api/hub/certificates/${certificate.id}/file`} target="_blank" rel="noopener noreferrer">Abrir arquivo <ArrowUpRight size={16}/></a></article>)}</div></div>:<div className="career-empty"><span className="career-empty-icon"><Award size={28}/></span><p>SEUS CERTIFICADOS</p><h2>Ainda não há certificados aqui.</h2><span>Registre o nome, a instituição, a data, as habilidades e o arquivo original em um só lugar.</span><div className="career-empty-actions"><button onClick={()=>setUploadOpen(true)}><Plus size={16}/> Adicionar primeiro certificado</button><button className="career-agent-link" onClick={onOpenAgent}>Planejar com o agente <ArrowRight size={16}/></button></div></div>)}
   {tab==='plano'&&<div className="career-plan"><div><p>PLANO DE EVOLUÇÃO</p><h2>Uma rota criada a partir<br/>dos seus objetivos.</h2><span>Antes de sugerir cursos ou oportunidades, vamos entender onde você quer chegar.</span><button onClick={onOpenAgent}>Conversar com Carreira & Tecnologia <ArrowRight size={16}/></button></div><ol><li><span>01</span><div><strong>Direção profissional</strong><p>Definir o tipo de oportunidade que você procura.</p></div><CheckCircle2 size={18}/></li><li><span>02</span><div><strong>Base técnica</strong><p>Mapear conhecimentos e próximos aprendizados.</p></div><CircleDot size={18}/></li><li><span>03</span><div><strong>Portfólio</strong><p>Transformar estudo e prática em evidências concretas.</p></div><CircleDot size={18}/></li></ol></div>}
   </div>
  </section>
  <footer className="career-footer">GABRIEL AI HUB <b>·</b> CARREIRA & CERTIFICADOS <span>ETAPA 02</span></footer>
 </main><Dialog open={uploadOpen} onOpenChange={open=>{if(!uploading){setUploadOpen(open);setUploadError('');}}}><DialogContent className="certificate-dialog"><DialogHeader><DialogTitle>Adicionar certificado</DialogTitle><DialogDescription>Registre os dados principais e anexe o comprovante original.</DialogDescription></DialogHeader><form onSubmit={uploadCertificate}><label>Nome do certificado<input name="title" required maxLength={140} placeholder="Ex.: Introdução à Cibersegurança"/></label><label>Instituição<input name="issuer" required maxLength={140} placeholder="Ex.: Cisco Networking Academy"/></label><div className="certificate-form-row"><label>Data de emissão<input name="issuedAt" type="date"/></label><label>ID da credencial <span>(opcional)</span><input name="credentialId" maxLength={120} placeholder="Código ou identificação"/></label></div><label>Habilidades <span>(separe por vírgulas)</span><input name="skills" maxLength={800} placeholder="Redes, Segurança, Linux"/></label><label className="certificate-drop"><FileText size={25}/><strong>Anexar comprovante</strong><span>PDF, JPG, PNG ou WebP · máximo de 8 MB</span><input name="file" type="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label>{uploadError&&<p className="certificate-form-error"><CircleAlert size={16}/>{uploadError}</p>}<div className="certificate-form-actions"><button type="button" onClick={()=>setUploadOpen(false)} disabled={uploading}>Cancelar</button><button type="submit" disabled={uploading}>{uploading?<><LoaderCircle className="spin" size={17}/> Salvando…</>:<>Salvar certificado <ArrowRight size={16}/></>}</button></div></form></DialogContent></Dialog></>;
}

function ProjectsSpace({onBack}:{onBack:()=>void}){
 const projects=[
  {title:'Gabriel AI Hub',area:'Produto pessoal',status:'Em construção',tone:'mint',icon:BrainCircuit,description:'A central privada que reúne seus espaços, conquistas e próximos passos.',next:'Definir a próxima entrega'},
  {title:'Portfólio de Engenharia',area:'Carreira & Tecnologia',status:'Planejamento',tone:'blue',icon:Code2,description:'Projetos técnicos, estudos e evidências para apresentar sua evolução.',next:'Separar os projetos principais'},
  {title:'Pesquisa IPE',area:'IPE Trading',status:'Em andamento',tone:'amber',icon:Globe2,description:'Materiais e análises que podem virar relatórios profissionais.',next:'Organizar fontes e entregáveis'},
 ];
 return <main className="projects-space" id="workspace" tabIndex={-1}><header className="projects-nav"><button onClick={onBack} className="projects-back"><ChevronLeft size={18}/> Voltar ao Hub</button><span className="projects-brand"><FolderKanban size={17}/> PROJETOS</span><span className="career-private"><ShieldCheck size={15}/> espaço pessoal</span></header><section className="projects-hero"><div><p>SEU ESPAÇO DE CRIAÇÃO</p><h1>Ideias que viram<br/><em>realidade.</em></h1><span>Reúna o que você está construindo, acompanhe o próximo passo e transforme intenção em entrega.</span></div><div className="projects-counter"><strong>{projects.length}</strong><span>exemplos de projetos</span><button disabled title="O cadastro de projetos ainda está em preparação">Cadastro em breve</button></div></section><section className="projects-content"><div className="projects-toolbar"><div><p>VISÃO GERAL</p><h2>O que está em movimento.</h2></div><span>Exemplos · ainda não são projetos cadastrados</span></div><div className="projects-grid">{projects.map(project=>{const Icon=project.icon;return <article key={project.title} className={'project-card '+project.tone}><div className="project-card-top"><span className="project-icon"><Icon size={22}/></span><small>{project.status}</small></div><p>{project.area}</p><h3>{project.title}</h3><span>{project.description}</span><div className="project-next"><small>PRÓXIMO PASSO</small><strong>{project.next}</strong><ArrowRight size={17}/></div></article>})}<article className="project-empty"><span><Plus size={22}/></span><p>PRÓXIMO PROJETO</p><h3>Abra espaço para uma nova ideia.</h3><button disabled title="O cadastro de projetos ainda está em preparação">Em breve</button></article></div></section><footer className="career-footer">GABRIEL AI HUB <b>·</b> PROJETOS <span>ETAPA 03</span></footer></main>;
}

function FocusSpace({onBack}:{onBack:()=>void}){
 const [done,setDone]=useState<number[]>([]);
 const tasks=[['Faculdade','Revisar conteúdo de IA e entregar o trabalho de POO'],['Concursos','Resolver 30 questões de Direito Constitucional'],['IPE Trading','Registrar a leitura do mercado no diário'],['Carreira','Separar um projeto para o portfólio']];
 const toggle=(index:number)=>setDone(items=>items.includes(index)?items.filter(item=>item!==index):[...items,index]);
 return <main className="focus-space" id="workspace" tabIndex={-1}><header className="focus-nav"><button onClick={onBack} className="projects-back"><ChevronLeft size={18}/> Voltar ao Hub</button><span className="projects-brand"><Target size={17}/> FOCO</span><span className="career-private"><ShieldCheck size={15}/> espaço pessoal</span></header><section className="focus-hero"><div><p>RITMO DE HOJE</p><h1>Uma coisa de cada vez.<br/><em>Com intenção.</em></h1><span>Experimente as sugestões abaixo. Este quadro é demonstrativo e as marcações não são salvas.</span></div><div className="focus-date"><TodayDate/></div></section><section className="focus-content"><div className="focus-primary"><div className="focus-section-head"><div><p>PRIORIDADES DO DIA</p><h2>O que merece sua atenção agora.</h2></div><span>{done.length}/{tasks.length} concluídas</span></div><div className="focus-task-list">{tasks.map(([area,title],index)=><button key={title} className={'focus-task '+(done.includes(index)?'is-done':'')} onClick={()=>toggle(index)}><span className="focus-check">{done.includes(index)?<CheckCircle2 size={18}/>:<CircleDot size={18}/>}</span><span><small>{area}</small><strong>{title}</strong></span><ArrowRight size={17}/></button>)}</div></div><aside className="focus-week"><p>SEMANA EM PERSPECTIVA</p><h2>Seu ritmo é construído nos detalhes.</h2><div className="week-bars" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/></div><p className="muted">O acompanhamento semanal ainda está em preparação.</p><div className="focus-note"><Target size={19}/><span>Hoje, avance em uma tarefa que deixe amanhã mais leve.</span></div></aside></section><footer className="career-footer">GABRIEL AI HUB <b>·</b> FOCO <span>ETAPA 04</span></footer></main>;
}

function LibrarySpace({onBack}:{onBack:()=>void}){
 const collections=[{label:'Faculdade',detail:'Aulas, exercícios, PDFs e referências da Engenharia da Computação.',count:'Em preparação',icon:GraduationCap,tone:'blue'},{label:'Concursos',detail:'Editais, questões, revisões e materiais de preparação.',count:'Em preparação',icon:BookOpen,tone:'amber'},{label:'IPE Trading',detail:'Pesquisas, relatórios, fontes e documentação profissional.',count:'Em preparação',icon:Globe2,tone:'violet'},{label:'Carreira',detail:'Cursos, certificados, currículo e desenvolvimento técnico.',count:'Em preparação',icon:BriefcaseBusiness,tone:'mint'}];
 const recent:string[][]=[];
 return <main className="library-space" id="workspace" tabIndex={-1}><header className="library-nav"><button onClick={onBack} className="projects-back"><ChevronLeft size={18}/> Voltar ao Hub</button><span className="projects-brand"><Layers3 size={17}/> BIBLIOTECA</span><span className="career-private"><ShieldCheck size={15}/> espaço pessoal</span></header><section className="library-hero"><div><p>SUA BASE DE CONHECIMENTO</p><h1>O que você aprende<br/><em>fica com você.</em></h1><span>Um lugar para reunir materiais, referências e arquivos que sustentam seus próximos passos.</span></div><div className="library-counter"><strong>—</strong><span>Biblioteca em preparação</span><button disabled>Arquivos em breve</button></div></section><section className="library-content"><div className="library-head"><div><p>COLEÇÕES</p><h2>Encontre pelo contexto.</h2></div><span>04 coleções planejadas</span></div><div className="library-collections">{collections.map(item=>{const Icon=item.icon;return <button disabled title="Esta coleção ainda está em preparação" key={item.label} className={'library-collection '+item.tone}><span className="library-collection-icon"><Icon size={22}/></span><div><small>{item.count}</small><h3>{item.label}</h3><p>{item.detail}</p></div><ArrowRight size={17}/></button>})}</div><div className="library-recent"><div className="library-head"><div><p>ADICIONADOS RECENTEMENTE</p><h2>O que entrou por último.</h2></div><span>Ainda sem arquivos cadastrados</span></div><div className="library-file-list">{recent.map(([title,meta,date])=><article key={title}><span><FileText size={20}/></span><div><strong>{title}</strong><small>{meta}</small></div><time>{date}</time><ArrowUpRight size={16}/></article>)}</div></div></section><footer className="career-footer">GABRIEL AI HUB <b>·</b> BIBLIOTECA <span>ETAPA 05</span></footer></main>;
}

function TodayDate(){
 const [date,setDate]=useState<Date|null>(null);
 useEffect(()=>{const update=()=>setDate(new Date());const timer=setTimeout(update,0);const interval=setInterval(update,60000);return()=>{clearTimeout(timer);clearInterval(interval);};},[]);
 return <time dateTime={date?.toISOString()}>{date?new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeZone:'America/Sao_Paulo'}).format(date):'Hoje'}</time>;
}

function StudioCover({onOpenHub,onChoose,onOpenCertificates,onOpenProjects,onOpenFocus,onOpenLibrary,onOpenSearch}:{onOpenHub:()=>void;onChoose:(id:AgentId)=>void;onOpenCertificates:()=>void;onOpenProjects:()=>void;onOpenFocus:()=>void;onOpenLibrary:()=>void;onOpenSearch:()=>void}){
 const stations=[
  {label:'Faculdade',detail:'Conhecimento hoje, opções amanhã.',icon:GraduationCap,tone:'blue',action:()=>onChoose('faculdade'),tag:'AGENTE',progress:'68%',next:'Revisar conteúdo de IA e entregar o trabalho de POO'},
  {label:'Concursos',detail:'Disciplina é o caminho para a estabilidade.',icon:BookOpen,tone:'amber',action:()=>onChoose('concursos'),tag:'AGENTE',progress:'42%',next:'Resolver 30 questões de Direito Constitucional'},
  {label:'IPE Trading',detail:'Estratégia, dados e consistência.',icon:Globe2,tone:'mint',action:()=>onChoose('ipe'),tag:'AGENTE',progress:'75%',next:'Analisar segmento e registrar no diário de trades'},
  {label:'Carreira & Tecnologia',detail:'Construindo uma carreira com propósito.',icon:BriefcaseBusiness,tone:'violet',action:()=>onChoose('carreira'),tag:'AGENTE',progress:'35%',next:'Atualizar portfólio e estudar uma nova ferramenta de IA'},
 ];
 return <main className="hub-cover studio-cover" id="workspace" tabIndex={-1}>
  <header className="cover-nav"><button className="cover-brand" onClick={onOpenHub} aria-label="Abrir painel do Gabriel AI Hub"><span className="cover-mark">G<span>·</span></span><span>Gabriel <small>AI HUB</small></span></button><nav className="studio-desktop-nav" aria-label="Navegação principal"><a className="is-active" href="#destinos">STUDIO</a><button onClick={onOpenFocus}>FOCO</button><button onClick={onOpenLibrary}>BIBLIOTECA</button><span title="Em preparação">ANOTAÇÕES · em breve</span><span title="Em preparação">INSPIRAÇÃO · em breve</span></nav><button type="button" className="studio-search" onClick={onOpenSearch} aria-label="Pesquisar no Hub" aria-haspopup="dialog"><Search size={17}/><span>Pesquisar no hub…</span><kbd>Ctrl K</kbd></button><span className="cover-private"><ShieldCheck size={15}/> Espaço pessoal</span></header>
  <nav className="studio-mobile-nav" aria-label="Navegação do Hub"><button onClick={onOpenSearch}><Search size={15}/> Pesquisar</button><button onClick={onOpenFocus}><Target size={15}/> Foco</button><button onClick={onOpenLibrary}><Layers3 size={15}/> Biblioteca</button></nav>
  <section className="studio-hero" aria-labelledby="cover-title"><div className="studio-hero-copy"><p className="cover-kicker"><Sparkles size={14}/><span>BOM TE VER POR AQUI, GABRIEL</span></p><h1 id="cover-title">Grandes planos<br/>se constroem no <em>dia a dia.</em></h1><p>Este é o seu espaço de evolução. Organize, execute e acompanhe o que te leva mais longe.</p><button className="cover-primary" onClick={onOpenHub}>Abrir central de agentes <ArrowRight size={17}/></button></div><aside className="focus-panel"><div className="focus-quote">“</div><p>GABRIEL AI HUB</p><strong>Disciplina transforma intenções em resultados.</strong></aside><article className="focus-card"><small><TodayDate/></small><h2>Foco de hoje</h2><p>Pequenas ações, grandes resultados.</p><button onClick={onOpenFocus} aria-label="Abrir foco de hoje"><ArrowRight size={17}/></button></article></section>
  <section className="studio-stations" id="destinos" aria-labelledby="destinations-title"><div className="studio-section-head"><p id="destinations-title">SEUS ESPAÇOS DE TRABALHO</p><span>04 áreas ativas</span></div><div className="studio-station-grid">{stations.map(item=>{const Icon=item.icon;return <button key={item.label} className={'studio-station '+item.tone} onClick={item.action}><div className="station-top"><span className="destination-icon"><Icon size={23}/></span><small>{item.tag}</small></div><h2>{item.label}</h2><p>{item.detail}</p><div className="station-progress"><span>Converse com seu agente especializado</span></div><div className="station-next"><small>SUGESTÃO PARA COMEÇAR</small><span>{item.next}</span><ArrowRight size={18}/></div></button>;})}</div></section>
  <section className="studio-shelves"><button onClick={onOpenCertificates} className="studio-shelf mint"><Award size={25}/><div><small>CERTIFICADOS</small><strong>Suas conquistas em um só lugar.</strong><span>Organize e acompanhe seus certificados e formações.</span></div><b>Ver certificados <ArrowRight size={15}/></b><em><ArrowUpRight size={22}/></em></button><button onClick={onOpenProjects} className="studio-shelf amber"><FolderKanban size={25}/><div><small>PROJETOS</small><strong>Ideias que viram realidade.</strong><span>Planeje, desenvolva e acompanhe seus projetos pessoais.</span></div><b>Ver projetos <ArrowRight size={15}/></b><em><ArrowUpRight size={22}/></em></button></section>
  <footer className="studio-footer"><span>GABRIEL AI HUB <b>·</b> Estudo <b>·</b> Disciplina <b>·</b> Progresso <b>·</b> Liberdade</span><span>Organized Hub <b>·</b> <i/> Seu espaço de trabalho.</span></footer>
 </main>;
}

export default function HubPage(){return <SidebarProvider><Hub/></SidebarProvider>;}
